site_name: Helasuno
repo_url: https://github.com/helasuno/lang
theme:
  logo: img/icon.png
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    primary: blue grey
    media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
use_directory_urls: false
nav:
  - Home: index.md
  - Changelog: changelog.md
  - FAQ: faq.md
  - Media: media.md
  - Getting Started:
    - Packaging & Setup: packaging_setup.md
    - VS Code Extension: vscode_ext.md
    - Tutorial: tutorial.md
  - Language:
    - Conventions: lang_conventions.md
    - Statements:
      - end: stmts/end.md
      - get: stmts/get.md
      - jump: stmts/jump.md
      - pause: stmts/pause.md
      - set: stmts/set.md
      - write/writeln: stmts/write.md
  - Developers:
    - Working on the Interpreter: development.md
extra:
  consent:
    title: Cookies Consent
    description: >-
      Cookies are used here only to the extent that they are required.
      It's unclear which cookies are used in the tool used to make this
      site so don't hesitate to reject cookies here.
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences